import './advant/advant.js';
import './colors/colors.js';
import './compare-like/compare-like.js';
import './desc/desc.js';
import './dev-pay/dev-pay.js';
import './images/images.js'
import './price/price.js';
import './stars/stars.js';
import './video/video.js';
